In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [2]:
!nvidia-smi

Fri Oct  6 00:06:20 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## Introdution to Tensors

* https://pytorch.org/docs/stable/tensors.html



In [3]:
# Scalar tensor
scalar = torch.tensor(1)
scalar

tensor(1)

In [4]:
# The numbers of dimensions of tensor
scalar.ndim

0

In [5]:
# Get tensor back as python int
scalar.item()

1

In [6]:
# Vector
vector = torch.tensor([1,2])
#shape: The numbers of iem by dimension
vector, vector.ndim, vector.shape

(tensor([1, 2]), 1, torch.Size([2]))

In [7]:
# Matrix
MATRIX = torch.tensor([[1,2], [2,2]])
MATRIX, MATRIX.ndim, MATRIX.shape

(tensor([[1, 2],
         [2, 2]]),
 2,
 torch.Size([2, 2]))

In [8]:
MATRIX[0]

tensor([1, 2])

In [9]:
TENSOR = torch.tensor([[1,2,3],[1,2,3],[1,2,3],])
TENSOR, TENSOR.ndim, TENSOR.shape

(tensor([[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]),
 2,
 torch.Size([3, 3]))

In [10]:
TENSOR[0 ]

tensor([1, 2, 3])

### Random Tensor

* https://pytorch.org/docs/stable/generated/torch.rand.html?highlight=rand#torch.rand

In [11]:
# Create a random tensor of size (3, 4), three lines and four columns
# random_tensor = torch.rand(3, 3, 4)
random_tensor = torch.rand(2, 3, 3) # (z, x, y)
random_tensor, random_tensor.dtype

(tensor([[[0.8781, 0.9162, 0.4595],
          [0.8853, 0.2110, 0.2403],
          [0.9200, 0.2255, 0.4924]],
 
         [[0.4185, 0.0357, 0.5570],
          [0.0290, 0.1443, 0.4832],
          [0.1453, 0.0831, 0.4194]]]),
 torch.float32)

In [12]:
random_tensor.ndim

3

In [13]:
random_tensor[0]

tensor([[0.8781, 0.9162, 0.4595],
        [0.8853, 0.2110, 0.2403],
        [0.9200, 0.2255, 0.4924]])

In [14]:
# Random tensor similar shape to an image
random_image_size_tensor = torch.rand(224, 244, 3) # color channel, height, width
print(random_image_size_tensor.ndim, random_image_size_tensor.shape)
print(random_image_size_tensor)

3 torch.Size([224, 244, 3])
tensor([[[0.2405, 0.7667, 0.6914],
         [0.0598, 0.0302, 0.6887],
         [0.9904, 0.0549, 0.8235],
         ...,
         [0.5260, 0.0013, 0.3678],
         [0.3363, 0.1946, 0.0922],
         [0.6779, 0.0280, 0.7791]],

        [[0.8933, 0.2261, 0.7100],
         [0.1487, 0.8604, 0.8705],
         [0.2772, 0.2111, 0.6019],
         ...,
         [0.3584, 0.4797, 0.4191],
         [0.0256, 0.3659, 0.5798],
         [0.6221, 0.4160, 0.3073]],

        [[0.5037, 0.3484, 0.0682],
         [0.4952, 0.8506, 0.2985],
         [0.7378, 0.8672, 0.3729],
         ...,
         [0.4349, 0.7390, 0.6669],
         [0.3969, 0.9228, 0.1604],
         [0.8458, 0.0172, 0.2918]],

        ...,

        [[0.9941, 0.4596, 0.1243],
         [0.7632, 0.1344, 0.9714],
         [0.9881, 0.8384, 0.5011],
         ...,
         [0.8460, 0.3652, 0.5119],
         [0.9688, 0.8408, 0.7840],
         [0.6207, 0.2518, 0.7235]],

        [[0.1582, 0.9399, 0.3560],
         [0.2118, 0

### Zeros and Ones Tensor

In [15]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Creating a range of tensors and tensors-like

In [17]:
# Use torch.range()
torch.range(0, 10)

<ipython-input-17-2a699d7e7367>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [18]:
# The same that range
one_to_ten = torch.arange(0, 10)

In [19]:
# Step
torch.range(start=0, end=1000, step=77)

<ipython-input-19-9dd7610be6d2>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(start=0, end=1000, step=77)


tensor([  0.,  77., 154., 231., 308., 385., 462., 539., 616., 693., 770., 847.,
        924.])

In [20]:
# Tensors like, new tensor with the same shape
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note: ** Tensor datatypes is one of 3 big erros you'll run into with pytorch & deep learning:


1.   Tensors not right datatype
2.   Tensors not right shape
3.   Tensors not on the right device



In [21]:
# Tensors float32
float_32_tensor = torch.tensor(
  [4., 3., 2.],
  dtype=None, # Datatype
  device='cpu',
  # device='cuda', # what device you tensor on
  requires_grad=False # Whether or not to track gradients with this tensor operation

)
float_32_tensor

tensor([4., 3., 2.])

In [22]:
# Convert the datatype of a tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([4., 3., 2.], dtype=torch.float16)

In [23]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)

In [24]:
float_32_tensor*int_32_tensor

tensor([12., 18., 18.])

### Getting information from tensors
1.   Tensors not right datatype - to get datatype from a tensor we can use tensor.dtype
2.   Tensors not right shape - to get the shape of a tensor we use tensor.shape or tensor.size()
3.   Tensors not on the right device to obtain the tensor's device use the tensor.device

In [25]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.1295, 0.0992, 0.2898, 0.8353],
        [0.0668, 0.4866, 0.0803, 0.1254],
        [0.0439, 0.0650, 0.1902, 0.2601]])

In [26]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [27]:
print(f"Datatype of tensor: {some_tensor.dtype}",)
print(f"Shape of tensor: {some_tensor.shape}",)
print(f"Device of tensor: {some_tensor.device}",)

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipuling Tensor(Tensors operations)

Tensor operations includes:
* Addition
* Subtraction
* Multiplication(Element-wise)
* Division
* Matrix multiplication

In [28]:
tensor = torch.tensor([1, 2, 3])
# Sun
tensor + 10

tensor([11, 12, 13])

In [29]:
# Multiply
tensor * 10

tensor([10, 20, 30])

In [30]:
# Subtration
tensor - 10

tensor([-9, -8, -7])

In [31]:
# Build-in operations functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [32]:
torch.add(tensor, 1)

tensor([2, 3, 4])

In [33]:
torch.divide(tensor, 2)

tensor([0.5000, 1.0000, 1.5000])

### Matrix multiplication

Two main ways of perfoming multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multplication

There are two rules that performing matrix multiplication needs to satisfy

1. The inner dimensions must match:
* (3, 2) @ (3, 2) won't work
* (2, 3) @ (3, 2) will work
* (3, 2) @ (2, 3) will work

The resulting matrix has the shape of the **outer dimensions**:
* (2, 3) @ (3, 2) -> (2, 2)
* (3, 2) @ (2, 3) -> (3, 3)

In [34]:
# Element wise multiplication
print(tensor, " * ", tensor, " = ", tensor*tensor) # element by element

tensor([1, 2, 3])  *  tensor([1, 2, 3])  =  tensor([1, 4, 9])


In [35]:
# Matrix multiplication
%%time
torch.matmul(tensor, tensor)

CPU times: user 0 ns, sys: 781 µs, total: 781 µs
Wall time: 789 µs


tensor(14)

In [36]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 132 µs, sys: 23 µs, total: 155 µs
Wall time: 160 µs


tensor(14)

###  One of the most common errors in deep learning (shape errors)


In [37]:
torch.matmul(torch.rand(10, 4), torch.rand(4, 4)).shape


torch.Size([10, 4])

In [38]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)
# torch.mm(tensor_A, tensor_B) # Alias

RuntimeError: ignored

In [39]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fiz our tensor shape issues, we can manipulete the shape of one of our tensors using transpode

Basically a transpose switches the axes or dimensions of a given tensor

In [41]:
tensor_B, tensor_B.shape

(tensor([[ 7., 10.],
         [ 8., 11.],
         [ 9., 12.]]),
 torch.Size([3, 2]))

In [40]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7.,  8.,  9.],
         [10., 11., 12.]]),
 torch.Size([2, 3]))

In [42]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: Tensor_A =  {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: Tensor_A =  {tensor_A.shape}, tensor_B = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <-- inner dimensions must match")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\n Output shape: {output.shape}")

Original shapes: Tensor_A =  torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: Tensor_A =  torch.Size([3, 2]), tensor_B = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <-- inner dimensions must match
tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

 Output shape: torch.Size([3, 3])


### Tensor Agregation: min, max, mean, sum, etc

In [43]:
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [45]:
torch.min(x), x.min

(tensor(0), <function Tensor.min>)

In [46]:
torch.max(x), x.max

(tensor(90), <function Tensor.max>)

In [47]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [48]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [49]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [50]:
# Find the position in tensor that has the minium value with argmin()
x.argmin()

tensor(0)

In [51]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

## Rashaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - returna a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - Combine multiple tensors on top of each other(vstack) or side by side (hstack)

* Squeeze - Remove 1 dimension from a tensor
* Unsqueeze - Add 1 dimension to a target tensor
* Permute - Return a view of the input dimensions permuted(swapped) in a certain way


In [59]:
import torch
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [60]:
# Reshape
x_reshaped = x.reshape(1, 10)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [61]:
# Reshape, the number of reshape result maybe the same of the orignal tensor
x_reshaped = x.reshape(10, 1) # dimensions (x1, x2,)
x_reshaped, x_reshaped.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]))

In [62]:
x_reshaped = x.reshape(5, 2) # dimensions (x1, x2,)
x_reshaped, x_reshaped.shape


(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [64]:
# Change view, similar to shape
z = x.view(1, 10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [65]:
# Changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:, 0]  = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [71]:
# Stack tensors on top of earch
x_stacked = torch.stack([x, x, x, x])
x_stacked, x_stacked.shape

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([4, 10]))

In [72]:
x_reshaped = x.reshape(1, 10)

print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
Previous shape: torch.Size([1, 10])

New tensor: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
New shape: torch.Size([10])


In [73]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
Previous shape: torch.Size([10])

New tensor: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
New shape: torch.Size([1, 10])


In [74]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels, height, width ]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing(Selecting data from tensors)

Similiar to indexing with numpy

In [1]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
[
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
]

In [3]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [10]:
x[0, 2, 2]

tensor(9)

In [11]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[0, 1, :], x[0, :, 0]

(tensor([4, 5, 6]), tensor([1, 4, 7]))

In [12]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [13]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

## Pytoch and Numpy

Numpy is a popular scientific numerical computing library

* Data in numpy , want in pytorch tensor

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:

* torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.
*torch.Tensor.numpy() - PyTorch tensor -> NumPy array.

In [16]:
# Numpy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # Warning, when converting from numpy -> pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [17]:
array.dtype

dtype('float64')

In [18]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [19]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [20]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Rerpoducbility(Trying to take random out of random)

To reduce the randomness in neural networks and pytorch comos the concept of a random seed
Essentially what the random seed does is flavour the randomness

* https://pytorch.org/docs/stable/notes/randomness.html

* https://en.wikipedia.org/wiki/Random_seed

In [1]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.7263, 0.5477, 0.0836, 0.6943],
        [0.1941, 0.9006, 0.0237, 0.6807],
        [0.0643, 0.4368, 0.1235, 0.4065]])

Tensor B:
tensor([[0.5376, 0.8927, 0.3306, 0.8415],
        [0.0683, 0.6618, 0.1675, 0.4412],
        [0.8901, 0.2218, 0.9769, 0.3771]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [4]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_S EED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

## Running tensors and pytorch objects on the GPUS(and making faster computations)



In [7]:
# Check for GPU with pytoch
import torch
torch.cuda.is_available()

True

In [8]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [9]:
# Count number of devices
torch.cuda.device_count()

1

### Putting tensors (and models) on the GPU

In [10]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [11]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()

TypeError: ignored

In [12]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [13]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')